import Foundation
import ChuteCore

coreSuites()
sessionSuite()
sessionColorSuite()
glyphSuite()
hookStateSuite()
hookInstallerSuite()
terminalParseSuite()
diagnosticsSuite()
finderActionsSuite()
licenseSuite()
actionRequestSuite()
localServersSuite()
nameDeriveSuite()
finderRevealSuite()
supportReportSuite()
pastedImageSuite()
systemVitalsSuite()
onboardingSuite()
agentTranscriptSuite()
resumeCommandSuite()
contextBufferSuite()
processMetricsSuite()
processIdentitySuite()
statusMenuSuite()

T.report()
