import Foundation
import ChuteCore

coreSuites()
sessionSuite()
sessionColorSuite()
sessionCommandsSuite()
glyphSuite()
hookStateSuite()
hookInstallerSuite()
terminalParseSuite()
diagnosticsSuite()
finderActionsSuite()
actionRequestSuite()
localServersSuite()
nameDeriveSuite()
finderRevealSuite()
supportReportSuite()
pastedImageSuite()
systemVitalsSuite()
onboardingSuite()
agentTranscriptSuite()
resumeCommandSuite()
contextBufferSuite()
processMetricsSuite()
processIdentitySuite()
statusMenuSuite()
aboutTextSuite()
confirmPromptSuite()
projectRootSuite()
finderTargetSuite()
treeRenderSuite()
argParseSuite()
signalSuite()

T.report()
